[package]
name = "sugoi-na"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.4"
clap = { version = "4.5.0", features = ["derive"] }
